# -*- coding: utf-8 -*-
"""one_hot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17VQHaOvrk6AAMy-17rB-HHg21C7LodMf
"""

import pandas as pd
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data['robot'] = (data['whoAmI'] == 'robot').astype(int)
data['human'] = (data['whoAmI'] == 'human').astype(int)
data = data.drop('whoAmI', axis=1)
data.head()